/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  StencilFirestore as StencilFirestore
} from './components/stencil-firestore/stencil-firestore';

declare global {
  interface HTMLStencilFirestoreElement extends StencilFirestore, HTMLStencilElement {
  }
  var HTMLStencilFirestoreElement: {
    prototype: HTMLStencilFirestoreElement;
    new (): HTMLStencilFirestoreElement;
  };
  interface HTMLElementTagNameMap {
    "stencil-firestore": HTMLStencilFirestoreElement;
  }
  interface ElementTagNameMap {
    "stencil-firestore": HTMLStencilFirestoreElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "stencil-firestore": JSXElements.StencilFirestoreAttributes;
    }
  }
  namespace JSXElements {
    export interface StencilFirestoreAttributes extends HTMLAttributes {
      
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
